---
- name: GIT CONFIG
  hosts: localhost
  tasks:
  - copy: 
      src:  "master.gitconfig"
      dest: "~/.gitconfig"
  - yum:
      name: jq
      state: latest
  - yum:
      name: bat
      state: latest
